#!/usr/bin/env python

import sip
# avoid QTextStream::hex shadowing built-in function
sip.setapi('QTextStream',2)
from PyQt4.QtGui import QApplication

import argparse, os, serial, sys, time

from striplib.strip       import Strip, MAGIC
from striplib.commands    import Command
from striplib.stripwidget import StripWidget

def main():
    a = QApplication(sys.argv)

    parser = argparse.ArgumentParser(description='striprevolution control widget')
    parser.add_argument('device', metavar='DEVICE', type=str, nargs='?', default=None,
                        help='serial device')
    parser.add_argument('--speed', metavar='SPEED', type=int, default=115200,
                        help='serial device baud rate')
    parser.add_argument('--timeout', metavar='TIMEOUT', type=int, default=1,
                        help='serial timeout in seconds')
    parser.add_argument('--debug', metavar='DEBUG', type=bool, default=False,
                        help='enable/disable debug output')
    args = parser.parse_args()

    w = StripWidget(args.device,args.speed,args.timeout,args.debug)
    w.show()

    return a.exec_()

if __name__ == '__main__':
    main()
